### ISSUE TITLE
bigwig issues

### ISSUE THREAD

**Issue by zhangjun-123** [jianhong/trackViewer#12]
Dear author :
       It is a great package to visualize peaks on high-througtht sequencing data. I can't see any tracks when i upload my bigwig file into trackviewer .My bigwig file is from deeptools' transformation.I don't konw why.Thank you for your help!

Zhangjun

**Comment by jianhong** [comment]
Could you please make sure the seqlevelsStyle are same for your selected ranges and your bigwig files?

**Comment by zhangjun-123** [comment]
Do you mean the chromosome name in the bigwig file ? I can use IGV software view the bigwig file,but no tracks on the trackviewer plot.

**Comment by jianhong** [comment]
Yes. If you are trying to get the signal by the seqname style in UCSC (eg. chr1), you can try to swith to ensembl style (eg. 1).
