### ISSUE TITLE
Trouble understanding the documentation for lolliplot

### ISSUE THREAD

**Issue by genegrad** [jianhong/trackViewer#13]
I have been trying to use lolliplot to display mutations. My gene of interest contains a lot of exons and has large intronic regions. As a result, I want to shrink the intronic regions, but I am having trouble understanding what the vignette at bioconductor is asking me to specify. From the vignette at bioconductor (last updated 9 February 2021), 

## by set percentage for features and non-features segments
xaxis <- c(50968014, 50968514, 50968710, 50968838, 50970514)
rescale <- c(.3, .4, .3)

I am not sure what the numbers are specifying and to what coordinates the values in rescale correspond to. 

For instance, while it is possible to guess that the "50968014, 50968514" correspond to the range "TYMP", I don't understand what "50968710" corresponds to.

I also don't understand the documentation for how to specify the scale via a data frame. What are the numbers from "from.start", "from.end", "to.start", and "to.end" supposed to correspond to?

**Comment by jianhong** [comment]
the percentage is for features and non-features segments And it is not related to the xaxis. The are different.
For example, the features are exons IRanges(50968014, 50968514) and IRanges(50968838, 50970514), And connected with a intron IRanges(50968515, 50968837). The percentage c(.3, .4, .3) is for exon IRanges(50968014, 50968514), intron  IRanges(50968515, 50968837) and exon IRanges(50968838, 50970514) separately. 

"from.start", "from.end", is the original coordinate, 
"to.start", and "to.end", is the rescaled coordinates. The IRanges(from.start, from.end) will be rescale to (to.start, to.end). 

Hope this will help.

**Comment by genegrad** [comment]
Thank you for the clarification. I have had some success, but I have run into additional obstacles. I have been trying to map mutations to the same gene, but to generate different figures for different resulting phenotypes. However for some phenotypes, I get an error.

Error in jitterLables(start(SNPs), xscale = c(start(ranges), end(ranges)),  : 
  order(coor) == 1:length(coor) are not all TRUE

I have no idea what is going on. Do you have any advice on what I should first approach when troubleshooting?

**Comment by jianhong** [comment]
That means you should sort the mutations before plot. Did you do that? If you still have trouble in plot, let me know. 
And also, did you tried to split the lollipop plot into multiLayers. That may also help.

**Comment by genegrad** [comment]
I am having a hard time understanding what you mean by sort. The only time sorting or ordering is mentioned in the vignette is in the context of the piestacks. 

The general idea of what I have been trying to do is to sort by

SNP <- sort(table$SNP)
sample.gr <- GRanges("chr1", IRanges(SNP, width=1, names=paste0("snp", SNP)))
lolliplot(sample.gr, features)

I haven't been able to succeed yet. The spreadsheet that I started should have already had my mutations sorted by genomic coordinate, from lowest to highest. Am I misunderstanding what I should be sorting by?

**Comment by jianhong** [comment]
Try to sort the SNPs by ignore the strand information. Let me know if it does not work.

**Comment by genegrad** [comment]
I haven't been using the strand information for any of my plotting

The information that I am trying at this point is just the numeric coordinate without the chromosome information. The exons were generated using a table that I copy-pasted from Ensembl.

**Comment by jianhong** [comment]
Do you mind to share your script and sample data to me to repeat the error message?

**Comment by genegrad** [comment]
I have invited you to my project repository.

**Comment by jianhong** [comment]
Sorry, I did not see the repository.
