### ISSUE TITLE
Plotting the exons on a gene as a track

### ISSUE THREAD

**Issue by oalavijeh** [jianhong/trackViewer#15]
Many thanks for the amazing package. I am trying to plot some SNPs against a known gene but I cannot get the exons to appear, the track only appears as a whole solid "lump". 

Example code:

gr <- GRanges("chr16", IRanges(1510427, 1612072, names="IFT140"))
trs <- geneModelFromTxdb(TxDb.Hsapiens.UCSC.hg38.knownGene, org.Hs.eg.db, gr=gr)

# using a GRange to plot the exon? 
features <- c(GRangesList(trs[[5]]$dat))
names(features) <- c(trs[[5]]$name)
flen <- elementNROWS(features)
## define the feature colors
features$fill <- rep(c("lightblue"), flen)

Error in .wrap_in_length_one_list_like_object(value, name, x) : 
  failed to coerce 'list(value)' to a CompressedGRangesList object of length 1

## define the feature heights
features$height <- c(.02)
Error in .wrap_in_length_one_list_like_object(value, name, x) : 
  failed to coerce 'list(value)' to a CompressedGRangesList object of length 1

Not sure what I am doing wrong here? 

Many thanks

**Comment by jianhong** [comment]
GRangesList is a list. You can try to change it to GRanges like this:
`features <- trs[[5]]$dat; names(features) <- c(trs[[5]]$name)`
or set the fill and height metadata like this for a GRangesList:
`features[[1]]$fill <- rep(c("lightblue"), flen); features[[1]]$height <- c(.02)`

Let me know if you still have questions.

Jianhong.

**Comment by oalavijeh** [comment]
Dear Jianhong, 

Many thanks that seemed to work. However, my exons look very "thin". Is there a way of opening them up or is it a product of the axis? Please see the picture below:

![image](https://user-images.githubusercontent.com/56344383/125469519-afa7f948-683f-4de7-8e37-d00dd8dc77d7.png)
