### ISSUE TITLE
hg 38 annotated variant file and TxDb.Hsapiens.UCSC.hg38.knownGene

### ISSUE THREAD

**Issue by smeeta** [jianhong/trackViewer#18]
Hi Jianhong 

I obtained my filtered .vcf which I annotated using hg38 using wannovar. However when I am using this to lolliplot using .vcf file using the "hg38" and "TxDb.Hsapiens.UCSC.hg38.knownGene" my gene names do not match.
ie I have 5 variants in gene "PCDHA7" after the plot is generated I get "PCDHB4" gene.  The coordinates match but the gene names are different. Any help would be great.

Thank you
Smeeta

**Comment by jianhong** [comment]
Could you share your script to repeat the issue?

**Comment by smeeta** [comment]
Hi Jianhong,

Thank you  for your email. Attached are the following files : 
1.CleanVar_JH_test.vcf.gz	7.4 kB	19/11/2021, 15:13:52
2.CleanVar_JH_test.vcf.gz.tbi	1.1 kB	19/11/2021, 15:13:59
3.Script.rtf	2.6 kB	19/11/2021, 15:16:41
4.Postion_GeneName_hg38_Ann.rtf	28.2 kB	19/11/2021, 15:14:39
5.Image.png	67.0 kB	19/11/2021, 15:18:17

- concern is why my image for chr 5 variants do not show the correct gene names instead show diff genes name at the base of the lolliplot.
Please do let me know if any other information is required.

regards
Smeeta
[trackViewer_vcf_lolliplot_JH_191121.zip](https://github.com/jianhong/trackViewer/files/7568457/trackViewer_vcf_lolliplot_JH_191121.zip)

**Comment by smeeta** [comment]
Hi Jianhong ,

Could you please let me know if you managed to solve the issue.

thank you
Smeeta

**Comment by jianhong** [comment]
I think you may want to check your transcript name more carefully. Please try to get the correct transcripts like following code:
<code>
n <- sapply(trs, function(.ele) .ele$name)
w <- which(n=="PCDHA7")
features <- trs[w]
names(features) <- n[w]
</code>
Please note, R index start from 1 but not 0.
