### ISSUE TITLE
lolliplot border width?

### ISSUE THREAD

**Issue by criphg** [jianhong/trackViewer#19]
There is some method to change the width of lines that link the balloons without enlarge the text labels? Something like mut_GRange$border.stroke?

**Comment by jianhong** [comment]
Did you tried `lwd`? Is that what you want?

`
library(trackViewer)
SNP <- c(10, 12, 1400, 1402)
sample.gr <- GRanges("chr1", IRanges(SNP, width=1, names=paste0("snp", SNP)))
sample.gr$lwd <- 3 ## change the line width
features <- GRanges("chr1", IRanges(c(1, 501, 1001),
width=c(120, 400, 405),
names=paste0("block", 1:3)))
lolliplot(sample.gr, features)
`
