### ISSUE TITLE
Re-adjust figure size of lollipopPlot and avoid x-axis cut off

### ISSUE THREAD

**Issue by nalomran** [jianhong/trackViewer#21]
Hi,

Thank you for this great visualization tool. I am new to trackViewer lollipopPlot and I am experimenting with making the plot. However, my plot looked very wide and have white space at the top of figure for some reason that I would like to know how re-adjust the width and height of the figure? I tried following the documentation but there is not any information on that. Also, I changed the value of cex but that did not help. Such problem also causes the x-axis labels to be cut off. I believe this can be resolve by re-adjusting the figure size, how do I do that?

I am using RStudio Version 1.2.5033 and trackViewer Version 1.24.2.

Here is my code:

    library(trackViewer)
    myfile = read.csv("myfile.bed",           header = FALSE, sep = "\t")
    > myfile
    V1       V2      V3     V4
    1 label1 27146879 #E1C877  5
    2 label2 27146883 #E7B105  1
    3 label3 27146913 #2F1CDB  1
    4 label4 27146957 #B169CD  1
    5 label5 27147054 #6EB934  1
    6 label6 27147099 #D4D592  1
    > sample.gr <- GRanges("chr6",   IRanges(myfile$V2, names=myfile$V1), color=myfile$V3, score=myfile$V4)
    > features <- GRanges("chr6", IRanges(myfile$V2))
    > sample.gr.rot <- sample.gr
    > sample.gr.rot$label.parameter.rot <- 70
    > lolliplot(sample.gr.rot, features, cex = 1.1, yaxis.gp = gpar(fontsize=18, lwd=2), ylab = FALSE, xaxis.gp = gpar(fontsize=11))

Here is the figure:
![image](https://user-images.githubusercontent.com/15256831/168484630-b85a0791-cbdd-4867-bb3d-8c489ab46bc9.png)

Thank you so much for your help in advance,
Best.

**Comment by jianhong** [comment]
@nalomran ,
Thank you for trying trackViewer to plot your data.
Did you tried to change your plot region size ratio?
Let me know how it work via:
```{r}
pdf("test.pdf", width=9, height=4)
lolliplot(sample.gr.rot, features, cex = 1.1, yaxis.gp = gpar(fontsize=18, lwd=2), ylab = FALSE, xaxis.gp = gpar(fontsize=11))
dev.off()
```

**Comment by xsun1229** [comment]
Hi @jianhong, I wonder if there's a parameter to adjust the font of xlab and ylab?

**Comment by xsun1229** [comment]
Never mind, ylab.gp worked!
