### ISSUE TITLE
Create Lollipop plot with different variant annotationsl indels, SNPs, etc.

### ISSUE THREAD

**Issue by FridoB** [jianhong/trackViewer#25]
I am trying to create a lollipop plot using trackViewer. I have used the cbioportal mutation mapper, but it is too limited. I was trying to create a plot that looks something like this [https://twitter.com/fridobruehl/status/1659563464665227264?s=20](url)

Not sure whether this is possible in trackViewer. I tried and failed to come up with different labels other than SNP.

**Comment by jianhong** [comment]
Thanks for sharing the idea here. Most of the questions should be answered here: https://bioconductor.org/packages/release/bioc/vignettes/trackViewer/inst/doc/lollipopPlot.html

If you have specific request, just let me know.

Jianhong.
