### ISSUE TITLE
lolliplot / Caterpillar layout: max.score limit

### ISSUE THREAD

**Issue by ngs-seqer** [jianhong/trackViewer#26]
Currently, lolliplot() does not create a "caterpillar" plot when a given socre is > 10. Could you make this max.limit configurable? I have a mixed dataset and want to keep my plot's layout consistently.

**Comment by ngs-seqer** [comment]
Currently, lolliplot() does not create a "caterpillar" plot when a given socre is > 10. Could you make this max.limit configurable? I have a mixed dataset and want to keep my plot's layout consistently.

**Comment by jianhong** [comment]
Good idea. At first i thought it will be hard to count if more than ten. Anyway more flexible is always better. will keep you posted.Best!Your sincerely,Jianhong OuOn May 25, 2023, at 9:46 AM, ngs-seeker ***@***.***> wrote:﻿
Currently, lolliplot() does not create a "caterpillar" plot when a given socre is > 10. Could you make this max.limit configurable? I have a mixed dataset and want to keep my plot's layout consistently.

**Comment by ngs-seqer** [comment]
Thanks!

**Comment by jianhong** [comment]
I updated the lollplot function with parameter lollipop_style_switch_limit in development version. Let me know if it does not work for you.
