### ISSUE TITLE
legend font size

### ISSUE THREAD

**Issue by ngs-seqer** [jianhong/trackViewer#27]
How can I change font size in the plot (esp. lolliplot)? 

For example, I want to keep the default font for the main plot, but use smaller one for the legend  --- i.e. "block1 / 2 /3" in the lolliplot (https://www.bioconductor.org/packages/devel/bioc/vignettes/trackViewer/inst/doc/lollipopPlot.html) 

Let me know. Thanks!

**Comment by jianhong** [comment]
You may want to try ```features$cex <- rep(0.5, length(features))```
Let me know if it does not work.

**Comment by wlyucl** [comment]
> You may want to try `features$cex <- rep(0.5, length(features))` Let me know if it does not work.

It worked. Thank you!
