### ISSUE TITLE
how can i modify and/or remove the lower legend? or overwrite?

### ISSUE THREAD

**Issue by storySG** [jianhong/trackViewer#28]
<img width="774" alt="Screen Shot 2023-07-03 at 19 19 38" src="https://github.com/jianhong/trackViewer/assets/128035644/db055682-0c5c-466e-90ba-5922a424ba32">

I wanted to plot all the exons of a gene. But I don't want them to be labeled below as exon1, exon2, etc... I just want to have one orange bar with the label "TP53".

EDIT: to clarify, i have the features as a simple GRanges object where i subset the exons of choice but it uses the names of each range as the legend (and GRanges requires unique names)

**Comment by storySG** [comment]
maybe this is already implemented but if there was a similar meta data column like:
`$label.parameter.draw <- FALSE`
that could be applied to the `features` _GRanges_ object that would be ideal!

**Comment by jianhong** [comment]
Hi,

Thank you for trying trackViewer to plot your data. I update the development trackViewer to meet your request.

You can try:
```
BiocManager::install("jianhong/trackViewer")
lolliplot(sample.gr, unname(features)) ## to remove the feature legends
names(features) <- rep("TP53", length(features))
lolliplot(sample.gr, features) ## only show the legends label as "TP53"
```

FYI, by removing the feature names, the feature legends will be removed.
