### ISSUE TITLE
problem when ploting multiple genes in one track with browseTracks()

### ISSUE THREAD

**Issue by lwf20** [jianhong/trackViewer#32]
Dear Jianhong,
Thanks for your wonderful package! it helps me a lot. 
however, I met a problem when I used browseTracks() function to visualize the track with multiple genes. if I used viewTracks() function, the output plot looks good(figure 1). but when I used browseTracks(), all gene features merge together(figure 2). I wonder what parameters I can set to make the genes track look like the output of viewTracks().
looking forward for your response.

figure1
![图片](https://github.com/jianhong/trackViewer/assets/81340626/0d9b4961-f68b-4915-ac6c-580359f68cf7)

figure2
![图片](https://github.com/jianhong/trackViewer/assets/81340626/0f51c85c-c8ab-4eed-8e36-97738c0868be)

here is my code:
```
grW <- parse2GRanges("8:85689000-85710000")
ids <- getGeneIDsFromTxDb(grW, txdb = txdb)
ID.transfer = read.csv("/data/Genome/mouse/GRCm39/mice_ensemble104_GRCm39_IDs.csv")
input_list = split(ID.transfer$geneName,ID.transfer$GeneID)
symbol = input_list[ids]
genes <- geneTrack(ids, txdb, symbol, asList=FALSE)

optSty <- optimizeStyle(trackList(D10, D0, genes), theme="safe")
trackListW <- optSty$tracks
viewerStyleW <- optSty$style
viewTracks(trackListW, gr=grW, viewerStyle=viewerStyleW)``

browseTracks(trackListW, gr=gr)

```

**Comment by jianhong** [comment]
Thank you for reporting this bug. I will try to fix this soon.

**Comment by jianhong** [comment]
I just updated the development version to fix this issue. Let me know if it does not work for you.

**Comment by lwf20** [comment]
yes, it works. thank you very much.
