### ISSUE TITLE
problem when adjust the min value of track with browseTracks()

### ISSUE THREAD

**Issue by lwf20** [jianhong/trackViewer#33]
Dear jianhong,
Thanks for your wonderful package.
I met a problem when I used browseTracks() to show my data.  After adjusting the min value of the track from 0 to 3, I found that the whole peak moved down rather than showing the region upper than 3, like this screenshot.
![图片](https://github.com/jianhong/trackViewer/assets/81340626/76a9ab02-3dc7-4f04-83c0-0c319596df21)
Could you give me some advice to solve this problem?

**Comment by jianhong** [comment]
Thank you for reporting this. The issue should be fixed in the last development version. Let me know if you have any question.

**Comment by lwf20** [comment]
yes, it worked. thank you very much!
