### ISSUE TITLE
can not modify the snp labels using label.parameter.label parameter

### ISSUE THREAD

**Issue by xsun1229** [jianhong/trackViewer#34]
Hi Jianhong,

I was trying to edit the SNP labels using  `label.parameter.label` parameter but noticed it didn't work. 

More specifically, the codes (from the tutorial) attached below didn't work. I cannot edit the names or remove some labels. 

```
## change the label text into user-defined names other than names of the sample.gr
sample.gr.rot$label.parameter.label <- names(sample.gr)
random_ids <- sample(seq_along(sample.gr), 5)
sample.gr.rot$label.parameter.label[random_ids] <- 
  paste("new label", random_ids)
random_ids <- sample(seq_along(sample.gr), 2)
sample.gr.rot$label.parameter.label[random_ids] <- NA ## remove some labels
lolliplot(sample.gr.rot, features, legend=legend)
```

I wonder if you have any suggestions about this? 

Thanks!
Xiaotong

**Comment by jianhong** [comment]
did you tried to change the names of the GRanges object?Best!Your sincerely,Jianhong OuOn Dec 26, 2023, at 11:49 AM, xsun1229 ***@***.***> wrote:﻿
Hi Jianhong,
I was trying to edit the SNP labels using  label.parameter.label parameter but noticed it didn't work.
More specifically, the codes (from the tutorial) attached below didn't work. I cannot edit the names or remove some labels.
## change the label text into user-defined names other than names of the sample.gr
sample.gr.rot$label.parameter.label <- names(sample.gr)
random_ids <- sample(seq_along(sample.gr), 5)
sample.gr.rot$label.parameter.label[random_ids] <- 
  paste("new label", random_ids)
random_ids <- sample(seq_along(sample.gr), 2)
sample.gr.rot$label.parameter.label[random_ids] <- NA ## remove some labels
lolliplot(sample.gr.rot, features, legend=legend)

I wonder if you have any suggestions about this?
Thanks!
Xiaotong

**Comment by xsun1229** [comment]
> did you tried to change the names of the GRanges object?Best!Your sincerely,Jianhong OuOn Dec 26, 2023, at 11:49 AM, xsun1229 ***@***.***> wrote:﻿ Hi Jianhong, I was trying to edit the SNP labels using label.parameter.label parameter but noticed it didn't work. More specifically, the codes (from the tutorial) attached below didn't work. I cannot edit the names or remove some labels. ## change the label text into user-defined names other than names of the sample.gr sample.gr.rot$label.parameter.label <- names(sample.gr) random_ids <- sample(seq_along(sample.gr), 5) sample.gr.rot$label.parameter.label[random_ids] <- paste("new label", random_ids) random_ids <- sample(seq_along(sample.gr), 2) sample.gr.rot$label.parameter.label[random_ids] <- NA ## remove some labels lolliplot(sample.gr.rot, features, legend=legend) I wonder if you have any suggestions about this? Thanks! Xiaotong —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

No I didn't. The Granges are generated at the beginning of the tutorial: 

```
SNP <- c(10, 100, 105, 108, 400, 410, 420, 600, 700, 805, 840, 1400, 1402)
sample.gr <- GRanges("chr1", IRanges(SNP, width=1, names=paste0("snp", SNP)))
lolliplot(sample.gr, features)
```

After generating the granges for SNPs and features, I jumped to the editing part. 

Actually I noticed this issue when plotting my own SNPs and features, it didn't work. So I tried to re-run the tutorial and the issue occurred. Not sure of there are issues on my end or the package...

Thanks!
Xiaotong

**Comment by jianhong** [comment]
try‘’’names(sample.gr) <- letters[seq_along(sample.gr)]‘’’Best!Your sincerely,Jianhong OuOn Dec 26, 2023, at 1:58 PM, xsun1229 ***@***.***> wrote:﻿

did you tried to change the names of the GRanges object?Best!Your sincerely,Jianhong OuOn Dec 26, 2023, at 11:49 AM, xsun1229 @.> wrote:﻿ Hi Jianhong, I was trying to edit the SNP labels using label.parameter.label parameter but noticed it didn't work. More specifically, the codes (from the tutorial) attached below didn't work. I cannot edit the names or remove some labels. ## change the label text into user-defined names other than names of the sample.gr sample.gr.rot$label.parameter.label <- names(sample.gr) random_ids <- sample(seq_along(sample.gr), 5) sample.gr.rot$label.parameter.label[random_ids] <- paste("new label", random_ids) random_ids <- sample(seq_along(sample.gr), 2) sample.gr.rot$label.parameter.label[random_ids] <- NA ## remove some labels lolliplot(sample.gr.rot, features, legend=legend) I wonder if you have any suggestions about this? Thanks! Xiaotong —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: @.>

No I didn't. The Granges are generated at the beginning of the tutorial:
SNP <- c(10, 100, 105, 108, 400, 410, 420, 600, 700, 805, 840, 1400, 1402)
sample.gr <- GRanges("chr1", IRanges(SNP, width=1, names=paste0("snp", SNP)))
lolliplot(sample.gr, features)

After generating the granges for SNPs and features, I jumped to the editing part.
Actually I noticed this issue when plotting my own SNPs and features, it didn't work. So I tried to re-run the tutorial and the issue occurred. Not sure of there are issues on my end or the package...
Thanks!
Xiaotong

**Comment by xsun1229** [comment]
`names(sample.gr) <- letters[seq_along(sample.gr)]` works for re-naming the SNPs, but it doesn't work for removing some SNP labels when plotting. 

Attached is my plot generated by track viewer. Since there are too many SNPs, I need to remove the labels for some SNP. So if 

```
random_ids <- sample(seq_along(sample.gr), 2)
sample.gr.rot$label.parameter.label[random_ids] <- NA ## remove some labels
```

works, it would be greatly helpful. 

<img width="1485" alt="Screenshot 2023-12-26 at 8 58 54 PM" src="https://github.com/jianhong/trackViewer/assets/62573051/10dfd8d9-7610-43c3-9798-3f4531e45cce">

**Comment by jianhong** [comment]
Will this work?trackViewer Vignette: lollipopPlotbioconductor.orgBest!Your sincerely,Jianhong OuOn Dec 26, 2023, at 11:01 PM, xsun1229 ***@***.***> wrote:﻿
names(sample.gr) <- letters[seq_along(sample.gr)] works for re-naming the SNPs, but it doesn't work for removing some SNP labels when plotting.
Attached is my plot generated by track viewer. Since there are too many SNPs, I need to remove the labels for some SNP. So if
random_ids <- sample(seq_along(sample.gr), 2)
sample.gr.rot$label.parameter.label[random_ids] <- NA ## remove some labels

works, it would be greatly helpful.
Screenshot.2023-12-26.at.8.58.54.PM.png (view on web)

**Comment by xsun1229** [comment]
> Will this work?trackViewer Vignette: lollipopPlotbioconductor.orgBest!Your sincerely,Jianhong OuOn Dec 26, 2023, at 11:01 PM, xsun1229 ***@***.***> wrote:﻿ names(sample.gr) <- letters[seq_along(sample.gr)] works for re-naming the SNPs, but it doesn't work for removing some SNP labels when plotting. Attached is my plot generated by track viewer. Since there are too many SNPs, I need to remove the labels for some SNP. So if random_ids <- sample(seq_along(sample.gr), 2) sample.gr.rot$label.parameter.label[random_ids] <- NA ## remove some labels works, it would be greatly helpful. Screenshot.2023-12-26.at.8.58.54.PM.png (view on web) —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

This is the tutorial I mentioned at the beginning. I tried the below commands but they didn't work. 

```
## change the label text into user-defined names other than names of the sample.gr
sample.gr.rot$label.parameter.label <- names(sample.gr)
random_ids <- sample(seq_along(sample.gr), 5)
sample.gr.rot$label.parameter.label[random_ids] <- 
  paste("new label", random_ids)
random_ids <- sample(seq_along(sample.gr), 2)
sample.gr.rot$label.parameter.label[random_ids] <- NA ## remove some labels
lolliplot(sample.gr.rot, features, legend=legend)
```

Thanks!

**Comment by jianhong** [comment]
May I know the version of your trackViewer? Could you please try to update the trackViewer to newest version or development version via 
```
BiocManager::install('jianhong/trackViewer')
```

**Comment by xsun1229** [comment]
> May I know the version of your trackViewer? Could you please try to update the trackViewer to newest version or development version via
> 
> ```
> BiocManager::install('jianhong/trackViewer')
> ```

Oh it worked after updating the trackViewer. my earlier one was 1.32.1. 

Thanks so much for your time!

**Comment by xsun1229** [comment]
Hi @jianhong, 

I wonder how do you usually save the output plots. 

I used 

```
pdf(file = pdf_bf,width = 20, height = 10)
lolliplot(gr_snp_bf,gr_domain,ylab="var.BF",lollipop_style_switch_limit=1)
dev.off()
```

but it seems it cannot save the SNP labels, I got plot like this

![Screenshot 2024-01-01 at 5 46 26 PM](https://github.com/jianhong/trackViewer/assets/62573051/acd4d774-9d9a-4f48-ba13-50081321dfe8)

But in the rstudio 'plot' window, I have this: 

![Screenshot 2024-01-01 at 5 45 58 PM](https://github.com/jianhong/trackViewer/assets/62573051/c04e0c78-aee4-4d4a-ad98-d83e1574438d)

There are dotted line linking the labels and the snps (although the labels are not shown completely). 

My labels are like this: 
![Screenshot 2024-01-01 at 5 46 14 PM](https://github.com/jianhong/trackViewer/assets/62573051/428b6adb-2b44-41e3-b21d-3ce603c8338b)

Thanks!

**Comment by jianhong** [comment]
Did you try to open the pdf file in Illustrator? I think this is an old issue that I did not fix yet. You may want to increase the height or width to get proper w:h ratio to make the labels in the plotting region.

**Comment by xsun1229** [comment]
@jianhong thanks for the reply! It seems I found something about issue but not sure how to figure it out. 

I was trying to filter the SNPs by `index_remove <- which(gr_snp_bf$score < 2)`, which leads to removing the label of No.106 SNP in `gr_snp_bf`. If I remove the label of this SNP, there is no labels in the output:

<img width="1486" alt="Screenshot 2024-01-02 at 4 04 50 PM" src="https://github.com/jianhong/trackViewer/assets/62573051/466b2796-f79b-4127-a6d7-0693de562e61">

but if I include the label of this SNP, I have the labels I need in the output:

<img width="1487" alt="Screenshot 2024-01-02 at 3 51 07 PM" src="https://github.com/jianhong/trackViewer/assets/62573051/fbaa6bae-3d1f-47e6-b6b9-850e072e1f1a">

The label of this SNP is: 

```
gr_snp_bf$label.parameter.label[106]
[1] "17:8623242:G:A"
class(gr_snp_bf$label.parameter.label[106])
[1] "character"
```

I think the class and format are the same with others. 

Since the length of gr_snp_bf is 212, I first thought I should include the label of the middle one. But when I tried another Grange, it seems not the case. The length of the new grange is 352, not matter include/exclude the label of middle SNP I got this:

<img width="1485" alt="Screenshot 2024-01-02 at 4 22 45 PM" src="https://github.com/jianhong/trackViewer/assets/62573051/3c634e28-01a3-402a-af10-8cf9a0c8c356">

Do you have any suggestion about this issue?

**Comment by jianhong** [comment]
Looks like the gr_snp_bf$label.parameter.label[106] is the first snp in the plot region. Could you please share me the GRanges object and the code of last plotting step?

**Comment by xsun1229** [comment]
@jianhong Sure. Attached is the data used in plotting. The code is 

```
pdf(file = "plot.pdf",width = 30, height = 10)
lolliplot(gr_snp_bf,gr_domain,ylab="var.BF",lollipop_style_switch_limit=1)
dev.off()
```

[gr_plotting.rdata.zip](https://github.com/jianhong/trackViewer/files/13814463/gr_plotting.rdata.zip)

**Comment by xsun1229** [comment]
I checked the data, yes, gr_snp_bf$label.parameter.label[106] is the first snp in the plot region. 

But when I include the first SNP in another data, I still cannot have the correct label. Attached is the other data. The first SNP in the plotting region is 1:43545092:C:A. It is the No.293 SNP in the grange. 

[gr_plotting2.rdata.zip](https://github.com/jianhong/trackViewer/files/13814523/gr_plotting2.rdata.zip)

**Comment by jianhong** [comment]
Thanks for the demo data. I updated the development version of trackViewer to patch this issue. Please try to update your package by ```BiocManager::install('jianhong/trackViewer')```. Let me know if you still have any question.

**Comment by xsun1229** [comment]
@jianhong Thanks for the prompt updates! The package works perfect now.
