### ISSUE TITLE
Lolliplot plus with the coverage without geneTrack

### ISSUE THREAD

**Issue by h20gg702** [jianhong/trackViewer#35]
Hi, Thank you for developing a beautiful package.
I am trying to make the Lolliplot and bigwig the coverage data like below (paste screenshots).
<img width="625" alt="スクリーンショット 2024-02-07 17 17 47" src="https://github.com/jianhong/trackViewer/assets/121539153/dd440c88-4dfb-407f-b5d5-ba0944c23aff">
I know there are some examples in Vignette like below, but this plot uses the genetrack() function. 
<img width="509" alt="スクリーンショット 2024-02-07 17 20 36" src="https://github.com/jianhong/trackViewer/assets/121539153/9870bf3a-8da0-4c17-bcdf-295e18f703f5">
I want to make a plot by `features <- GRanges("chr1", IRanges(c(1, 501, 1001), 
                                    width=c(120, 400, 405),
                                    names=paste0("block", 1:3)))` 
<img width="577" alt="スクリーンショット 2024-02-07 17 22 33" src="https://github.com/jianhong/trackViewer/assets/121539153/2d92ebce-0a3b-4127-ae79-b58e81f84783">

Are there any methods to make the plot?
Thanks in advance.

**Comment by jianhong** [comment]
I did not understand your question. Do you mean you want to plot the lollipops on the other side of coverages?

**Comment by h20gg702** [comment]
I want to combine these two plots. 
<img width="562" alt="スクリーンショット 2024-02-07 17 15 34" src="https://github.com/jianhong/trackViewer/assets/121539153/1ab817c1-71ef-4fd9-abfb-9164eb401246">
<img width="730" alt="スクリーンショット 2024-02-07 17 16 16" src="https://github.com/jianhong/trackViewer/assets/121539153/9b49eceb-eb72-492b-b29c-e323be14f2ab">

**Comment by jianhong** [comment]
Could you tell me why [this](https://bioconductor.org/packages/release/bioc/vignettes/trackViewer/inst/doc/lollipopPlot.html#Plot_the_lollipop_plot_with_the_coverage_and_annotation_tracks) does not fit your requirement?

**Comment by h20gg702** [comment]
I need to replace the following part of that script with something because I want a customized track. Thanks for your help.

gene <- geneTrack(get("HSPA8", org.Hs.egSYMBOL2EG), TxDb.Hsapiens.UCSC.hg19.knownGene)[[1]]

________________________________

**Comment by jianhong** [comment]
I updated the package to plot something like this
![image](https://github.com/jianhong/trackViewer/assets/5640707/04bf0740-f54e-4403-87ca-3ac159b37b5b)
with the customized geneTrack eg
```{r}
dat <- gene$dat
mcols(dat) <- NULL
dat <- subsetByOverlaps(dat, gr)
dat$feature <- 'exon' # feature is required
dat$featureID <- paste0('name', seq_along(dat)) # treat each as single exon gene
dat$color <- sample(seq.int(7), length(dat), replace = TRUE) # set the color
dat$height <- sample(c(0.5, 1, 2), length(dat), replace = TRUE) # set the height
dat$hide_label <- TRUE # do not add labels to the block
gene <- new('track', dat=dat, dat2=SNPs, type='gene', name='a name')
optSty <- optimizeStyle(trackList(fox2, gene), theme="col")
trackList <- optSty$tracks
viewerStyle <- optSty$style
vp <- viewTracks(trackList, gr=gr, viewerStyle=viewerStyle)
```
Try to install the devel version to repeat the plot by `BiocManager::install('jianhong/trackViewer')`. The version number is >= 1.39.10.

**Comment by h20gg702** [comment]
Thanks for the awsome update! I just wondering if you could show the legend like figure below. 
<img width="577" alt="スクリーンショット 2024-02-08 12 00 53" src="https://github.com/jianhong/trackViewer/assets/121539153/d221610e-481a-456d-9ab9-9f46a44a7c12">

Also, this is not related to this thread..., but in the figure below, is there any function that shows the legend? which color indicates what? 
<img width="761" alt="スクリーンショット 2024-02-08 12 04 06" src="https://github.com/jianhong/trackViewer/assets/121539153/76ce18fc-f8dd-4106-b01c-a60b3adf613e">

**Comment by jianhong** [comment]
For legend is difficult because I don't have a good idea to locate them. 
For the second question, the first element of color will fill dat and the second element of color will fill dat2. Please Note that the signal is accumulated by operation `+`.

**Comment by h20gg702** [comment]
> For legend is difficult because I don't have a good idea to locate them. For the second question, the first element of color will fill dat and the second element of color will fill dat2. Please Note that the signal is accumulated by operation `+`.

I see. Thank you for developing this awsome package!
