### ISSUE TITLE
heightDist does not work

### ISSUE THREAD

**Issue by h20gg702** [jianhong/trackViewer#36]
Hi, I faced a problem that heightDist does not work when I used the following script. Do you know the solution? Thank you.
`A <- new('track', dat=DMR_gr, type='gene', name='DMR_anno')
B <- new('track', dat=features, dat2=pop, type='gene', name='B')
C2 <- importScore(file.path(bw.files1[1]),
                        format="BigWig",
                        ranges=gr)
C1 <- importScore(file.path(bw.files4[1]),
                          format="BigWig",
                          ranges=gr)
C2$dat2 <- C1$dat
optSty <- optimizeStyle(trackList(A,B,C, heightDist = c(0.1, 1, 0.25)), theme="col")
trackList <- optSty$tracks
viewerStyle <- optSty$style
vp <- viewTracks(trackList(A,B, C), gr=gr, viewerStyle=viewerStyle, operator="+")`

**Comment by h20gg702** [comment]
> Hi, I faced a problem that heightDist does not work when I used the following script. Do you know the solution? Thank you. `A <- new('track', dat=DMR_gr, type='gene', name='DMR_anno') B <- new('track', dat=features, dat2=pop, type='gene', name='B') C2 <- importScore(file.path(bw.files1[1]), format="BigWig", ranges=gr) C1 <- importScore(file.path(bw.files4[1]), format="BigWig", ranges=gr) C2$dat2 <- C1$dat optSty <- optimizeStyle(trackList(A,B,C, heightDist = c(0.1, 1, 0.25)), theme="col") trackList <- optSty$tracks viewerStyle <- optSty$style vp <- viewTracks(trackList(A,B, C), gr=gr, viewerStyle=viewerStyle, operator="+")`

Hi, I solved by `vp <- viewTracks(trackList(A,B, C,, heightDist = c(0.1, 1, 0.25))), gr=gr, viewerStyle=viewerStyle, operator="+")`, but my figures lacks y-axis number...

**Comment by jianhong** [comment]
Nice to know you figured out it by yourself. You may want to check the [documentation](https://bioconductor.org/packages/release/bioc/vignettes/trackViewer/inst/doc/changeTracksStyles.html#Adjust_the_y-axis) here first. If you still have trouble in get the y-axis please let me know.

**Comment by jianhong** [comment]
Maybe I should add the documentation like this: `setTrackYaxisParam(trackList[[2]], 'label', TRUE)`

**Comment by h20gg702** [comment]
Thanks. It works well!
