### ISSUE TITLE
Is the legend transparency level modifiable? 

### ISSUE THREAD

**Issue by xsun1229** [jianhong/trackViewer#37]
Hi Jianhong,

I am using the following codes to add legend for each dot. 

```
# from version 1.21.8, users can also try to set legend 
# as a column name in the metadata of GRanges.
sample.gr.newlegend <- sample.gr
sample.gr.newlegend$legend <- LETTERS[sample.gr$color]
lolliplot(sample.gr.newlegend, features, legend="legend")
```

But it seems too transparent, I wonder if I can modify the transparency level ? 

![image](https://github.com/jianhong/trackViewer/assets/62573051/253151fc-7ccc-4105-a59e-1f3e87b060bb)

Thanks
Xiaotong

**Comment by jianhong** [comment]
Sorry, I missed this issue. Could you please share me a pseudo-code to repeat the issue?

Jianhong.

**Comment by xsun1229** [comment]
Thanks for the reply! 
Attached are the data and codes I used. 

[test.rdata.zip](https://github.com/jianhong/trackViewer/files/14621244/test.rdata.zip)

```
 pdf(file ="test.pdf",width = 15, height = 15)
 lolliplot(gr_snp_combine_bf,gr_domain,ylab="log2(var.BF)",legend = "legend",lollipop_style_switch_limit=1)
 dev.off()
```

**Comment by jianhong** [comment]
Thank you for sending the test data. I updated the development version to overcome this issue. Let me know if it does not work for you.

Jianhong.

**Comment by xsun1229** [comment]
Thank you for the quick update!

I noticed that you utilized a package called 'txdbmaker', which necessitates a more recent version of R along with additional dependencies. Currently, I'm encountering difficulties with these updates. I'll let you know if any problems persist after successfully installing them.

Appreciate your assistance once more!

Xiaotong

**Comment by jianhong** [comment]
The change were also pushed to RELEASE_3_18 branch. Please try to install it via
```{r}
BiocManager::install('jianhong/trackViewer@RELEASE_3_18')
```

**Comment by xsun1229** [comment]
Thanks! This command works perfectly. 

For the plot, it seems the text is good, but the legend color still looks lighter than the main figure.
![image](https://github.com/jianhong/trackViewer/assets/62573051/61adc0d1-5f42-4773-909c-38c7c29f9775)

**Comment by xsun1229** [comment]
There's no rush to make modifications, as I've managed to address this issue in my plotting by copying the dot from the main figure. Just wanted to let you know about this issue. :)
