### ISSUE TITLE
Custom legend stacking and position

### ISSUE THREAD

**Issue by zx8754** [jianhong/trackViewer#39]
From this:

![image](https://github.com/user-attachments/assets/6485390b-ba86-424e-b569-d4a340a52ff0)

To this:

![image](https://github.com/user-attachments/assets/55f6f4c7-568f-458c-9874-8ce888e61f1f)

And being able to choose the location: bottom, left, top, right? I think, legend position should already dictate the stacking the labels horizontally or vertically, like in ggplot.

Relevant SO post:

 - [Is there a way to move the legend in a trackViewer lollipopPlot and/or change its orientation?](https://stackoverflow.com/q/78206801/680068)

**Comment by jianhong** [comment]
Thank you for sharing this. I add a new parameter `legendPosition` to `lolliplot`.  To install last version, please try ```BiocManager::install('jianhong/trackViewer@devel')```
Let me know if it does not work for you.

**Comment by zx8754** [comment]
Thank you @jianhong, I couldn't test it, I have unrelated package update issues with R.

Feel free to close this issue if it worked for you.
