### ISSUE TITLE
make rescale more user-friendly

### ISSUE THREAD

**Issue by LiNk-NY** [jianhong/trackViewer#4]
Hi JianHong, @jianhong 

Could you please make the `rescale` argument in `lolliplot` function more user-friendly
so that the user is able to rescale the x-axis easily?
The input could be a factor with the same length as the `features` argument that
could also include the non-coding regions. 

Alternatively, this can be done programmatically so that the entire region is plotted
without having to scale manually and possibly add markers that denote non-coding
regions (`-//-`).

Best,
Marcel

**Comment by jianhong** [comment]
Hi Marcel,

Thank you for suggestion. I will put it into TODO list.

**Comment by LiNk-NY** [comment]
Thank you JianHong. I'm looking forward to it! :)

**Comment by jianhong** [comment]
It is available in the newest development version.

**Comment by LiNk-NY** [comment]
Wow! Thanks! I will check it out. 
Best,
Marcel
