### ISSUE TITLE
How to display data tracks as line graphs

### ISSUE THREAD

**Issue by zkhuang2012** [jianhong/trackViewer#41]
I want to display data tracks as line graphs. I try change the tracktype by trackList[[4]]@style@tracktype <- "line" and the data tracks are still displayed as histogram.

**Comment by jianhong** [comment]
I just pushed a patch to development version to make it possible. Please try
```{r}
BiocManager::install('jianhong/trackViewer')
detach('package:trackViewer', unload=TRUE)
library(trackViewer)
viewTracks(...)
```

Let me know if it does not work for you.

**Comment by zkhuang2012** [comment]
It works, thank you.
