### ISSUE TITLE
scale bar

### ISSUE THREAD

**Issue by biofisherman** [jianhong/trackViewer#5]
Hi Jianhong,

Very handy tool!

I am wondering how could I control the scale bar? Sometimes it shows up, sometimes not.

I didn't find the argument of scale bar in your manual.

Thanks,

Weiyan

**Comment by jianhong** [comment]
currently you can access the scale bar by directly assign values for track@style@xscale@from, track@style@xscale@to, and track@style@xscale@label. You may want to try to set unit to native.

**Comment by jianhong** [comment]
It is update. you can set the value like this:

setTrackXscaleParam(trackList[[1]], attr="position", value=list(x=122929700, y=3, label=200))

The label is a number for example you can set it as 1000 as you want.

**Comment by biofisherman** [comment]
Hi Jianhong,
when I run the setting as you suggested, I got the error
`Error in setTrackXscaleParam(trackList[[2]], attr = "position", value = list(x = 122929675, : attr must be a slot name of xscale object`

plus, I installed the new version on github.

Thanks

**Comment by jianhong** [comment]
Could you double check that by packageVersion("trackViewer")

Vignette were rebuilt without any error. See: https://bioconductor.org/packages/devel/bioc/vignettes/trackViewer/inst/doc/trackViewer.html#adjust-the-x-axis-or-the-x-scale

**Comment by biofisherman** [comment]
Hi Jianhong,
Thank you very much for all your help. It works right now when I used the latest version 1.21.13. The last time one I used was 1.21.12.

Best,

Weiyan
