### ISSUE TITLE
getGeneIDsFromTxDb missing

### ISSUE THREAD

**Issue by fengyq** [jianhong/trackViewer#8]
Hi,
Thank you for providing the great package, the getGeneIDsFromTxDb function is missing in the bioconductor version.
Best

**Comment by badoi** [comment]
You'll have to update R and bio conductor versions. I have R v3 and going to R v4 did the trick.

**Comment by smeeta** [comment]
> You'll have to update R and bio conductor versions. I have R v3 and going to R v4 did the trick.

hi Badoi,

Any insight as to why the genes in  my .vcf annovar hg38 annotated variants and those in lolliplot are different ?

thank you
Smeeta

**Comment by badoi** [comment]
Please open up a new ticket with the GitHub managers. I am a user.

**Comment by smeeta** [comment]
Thank you for the informing.  Did not realise that. Apologies ! Will direct to the Tracker Viewer team at GitHub
