### ISSUE TITLE
Hide bottom legend

### ISSUE THREAD

**Issue by neobernad** [jianhong/trackViewer#9]
Hi!

I would like to know if it would be possible to hide the names of the features. For instance [this example](https://www.bioconductor.org/packages/release/bioc/vignettes/trackViewer/inst/doc/trackViewer.html#lolliplot):

```r
SNP <- c(10, 12, 1400, 1402)
sample.gr <- GRanges("chr1", IRanges(SNP, width=1, names=paste0("snp", SNP)))
features <- GRanges("chr1", IRanges(c(1, 501, 1001), 
                                    width=c(120, 400, 405),
                                    names=paste0("block", 1:3)))
lolliplot(sample.gr, features)
```
It shows three items: `blocks1`, `blocks2` and `blocks3`.
Is there anyway to hide them?

Thanks,
José Antonio

**Comment by jianhong** [comment]
Did you tried to remove the names of features?

Best!

Your sincerely,

Jianhong Ou

**Comment by neobernad** [comment]
Hi @jianhong,

Thanks that worked! I was trying to set `names=c()` or `names=list()` and it was easier than I thought!

Best,
José Antonio
